### ISSUE TITLE
Matlab core function `struct ` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#48]
## 🚀 Feature Request

Function struct is not implemented, yet.

## 🔈 Motivation

It would be great to have an implementation of struct function.

## 📝 Expected Results

```matlab
S1 = struct('a',"Sausage","b",[1,5,0.15]);
s.a = "Sausage";
s.b = [1,5,0.15];

assert(s.a == S1.a)
```

**Comment by chaoqing** [comment]
Partially implemented in recent commits. struct creator for cell values still missing.

**Comment by APgEDo** [comment]
It would be great if {cell} values would be taken care of too, as results differ for cell values and arrays.
For me the above unit test does not work when I convert it to Python, as it results in `NameError: name 's' is not defined` for `s.a = "Sausage"`

**Comment by chaoqing** [comment]
Yes the upper unit test do not work because in Python object can not be referenced before creation. You can change the original matlab by insert a `s = struct()` at beginning and then try the generated unit test again.

Matlab support implicit object creation which is not supported in Python and I consider this behavior not robust and portable in programmer's view. In this case I suggest always update the Matlab code first.

**Comment by APgEDo** [comment]
Yes, you are right - by adding `s = struct( )` to Matlab or Python it works, meaning that Python needs a hint what type of variable you have.
