### ISSUE TITLE
Matlab core function `not` support

### ISSUE THREAD

**Issue by APgEDo** [mat2py/mat2py#49]
## 🚀 Feature Request

not is a fundamental Matlab function not implemented, yet.

## 🔈 Motivation

For unit testing I need the matrix capabilities of 'not'

## 📝 Expected Results

```matlab
X = [[0, 0, 3, 13]; [5, 11, 10, 8]; [9, 7, 0, 12]; [4, 14, 15, 0]]
NX = ~X
assert(isequal(NX, [[1, 1, 0, 0]; [0, 0, 0, 0]; [0, 0, 1, 0]; [0, 0, 0, 1]]))
A = ~true
assert(A == 0)
```

**Comment by chaoqing** [comment]
Actually `not` is also defined the same way as `_any`. You can import it manually `from mat2py.core.ops import _any, _not`.

I can explain how this issue emerge. `not` is a key word in Python but not in Matlab, which means you can do `not = 1` in Matlab. Luckily Matlab forbid variables start with underscore. So I decided to add prefix `_` to all key words inside Python but not in Matlab, in this way name collision do not happen. The solution also apply to mat2py keywords like `M`. 

However there is one drawback of this solution. Inside Python variables/functions start with underscore will be considered as private so when `from mat2py.core import *` they will not be imported. That's why it must be import manually. I may update `mh_python` to include the import automatically but I think that is not elegant.

**Comment by APgEDo** [comment]
Ah, right - so it is more or less a question of getting this private function and when manually importing it it works for me, so I will close this issue. Thanks!

**Comment by chaoqing** [comment]
I have taken care of the `__all__`, now you should not need to import manually any more.
